apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vbjki87qo-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-ecea9d29de.keu7.p3.openshiftapps.com/rhtap/rhtap-qe:035f118ce9e9c1ce263ad8c99b6a38267c52cc2f@sha256:c088b1d2439b92ba87591c506dffafa5c323cda1ca0c2818cdf436bfe8f78658
          name: container-image
